- name: Run Vulture Matrix
        run: |
          npm install axios
          node vulture-gen.js
          node sitemap-generator.js
          node ping-engines.js
          node social-distributor.js # NEW STEP
